import React from "react"
export const betarray = [
  { num: 0, color: "green", chip: null },
  { num: 3, color: "red", chip: null },
  { num: 6, color: "black", chip: null },
  { num: 9, color: "red", chip: null },
  { num: 12, color: "red", chip: null },
  { num: 15, color: "black", chip: null },
  { num: 18, color: "red", chip: null },
  { num: 21, color: "red", chip: null },
  { num: 24, color: "black", chip: null },
  { num: 27, color: "red", chip: null },
  { num: 30, color: "red", chip: null },
  { num: 33, color: "black", chip: null },
  { num: 36, color: "red", chip: null },
  { num: "1:2", color: "simple", chip: null },
  { num: 2, color: "black", chip: null },
  { num: 5, color: "red", chip: null },
  { num: 8, color: "black", chip: null },
  { num: 11, color: "black", chip: null },
  { num: 14, color: "red", chip: null },
  { num: 17, color: "black", chip: null },
  { num: 20, color: "black", chip: null },
  { num: 23, color: "red", chip: null },
  { num: 26, color: "black", chip: null },
  { num: 29, color: "black", chip: null },
  { num: 32, color: "red", chip: null },
  { num: 35, color: "black", chip: null },
  { num: "1:2", color: "simple", chip: null },
  { num: 1, color: "red", chip: null },
  { num: 4, color: "black", chip: null },
  { num: 7, color: "red", chip: null },
  { num: 10, color: "black", chip: null },
  { num: 13, color: "black", chip: null },
  { num: 16, color: "red", chip: null },
  { num: 19, color: "red", chip: null },
  { num: 22, color: "black", chip: null },
  { num: 25, color: "red", chip: null },
  { num: 28, color: "black", chip: null },
  { num: 31, color: "black", chip: null },
  { num: 34, color: "red", chip: null },
  { num: "1:2", color: "simple", chip: null },
]
export const subbetarray = [
  { num: "1st 12", color: "b1black" },
  { num: "2nd 12", color: "b2black" },
  { num: "3rd 12", color: "b3black" },
  { num: "1-19", color: "simple" },
  { num: "Even", color: "simple" },
  { num: "", color: "red" },
  { num: "", color: "black" },
  { num: "Even", color: "simple" },
  { num: "19-36", color: "simple" },
]
